#!/bin/bash

cd ./LaTeX-Workshop/dev # Clone git repo from https://github.com/James-Yu/LaTeX-Workshop

python pkgcommand.py -i ../../eekhof.cwl -o ../../ # Generate JSON for VSCode-Completion from provided CWL-file #TODO SEEMS to output some code, could be tried to be suppressed with &>/dev/null , but try if script then still executes properly

cd ..
cd ..

# Check if a personal data file is given in the directory of the install script (Contains three lines: Firstname, Surname, Matrikelnummer)
PERSONALDATAFILE=personaldata.txt
if [ -f "$PERSONALDATAFILE" ]; then
    echo "$PERSONALDATAFILE exists, reading data."
    firstname=$(awk 'NR==1' $PERSONALDATAFILE)
    surname=$(awk 'NR==2' $PERSONALDATAFILE)
    matrikelnummer=$(awk 'NR==3' $PERSONALDATAFILE)
    echo "Firstname: $firstname"
    echo "Surname: $surname"
    echo "Matrikelnummer: $matrikelnummer"
else 
    echo "$PERSONALDATAFILE does not exist, please provide information:"
    echo What is your first name?
    read firstname
    echo What is your surname?
    read surname
    echo What is your Matrikelnummer?
    read matrikelnummer
fi

# Ensure necessary folders exist:
mkdir -p ~/texmf/tex/latex/
mkdir -p ~/texmf/bibtex/

# Test if file exists already, i. e. if texhash-command needs to be run after installation:
if test -f "$HOME/texmf/tex/latex/eekhof.sty"; then
    newinstall=false
else
    newinstall=true
fi


sed -e "s/FIRSTNAMEHERE/$firstname/g" -e "s/SURNAMEHERE/$surname/g" -e "s/MATRIKELNUMMERHERE/$matrikelnummer/g" eekhof.sty > ~/texmf/tex/latex/eekhof.sty # Installs package to proper place after inserting personal parameters
cp eekhof.json ~/texmf/cwl/eekhof.json # Installs VSCode completion file
cp eekhof.bst ~/texmf/bibtex/bst/eekhof.bst # Installs custom bibstyle #TODO Seems to be the wrong place, is not found

# If neccessary run texhash:
if $newinstall ; then
    echo "This seems to be the first install of this package, running texhash..."
    texhash
else
    echo "A version of this package seems to already have been installed once, no need to run texhash."
fi
echo "Thank you $firstname $surname. The Eekhof-LaTeX-Package and its autocompletion-JSON for VSCode have been successfully installed."